export const SET_RECIPES = "SET_RECIPES";
export const SET_DETAILED_RECIPE = "SET_DETAILED_RECIPE";
export const SET_EDIT = "SET_EDIT";
export const DISABLE_EDIT_MODE = "DISABLE_EDIT_MODE";
export const SET_RECIPE_TITLE = "SET_RECIPE_TITLE";
export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const SET_IMAGE = "SET_IMAGE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_DESCRIPTION = "SET_DESCRIPTION";

export const SET_SERVER_RESPONSE = "SET_SERVER_RESPONSE";
export const ENABLE_MODAL = "SET_MODAL_VISIBLE";
export const DISABLE_MODAL = "DISABLE_MODAL";