export const SET_RECIPES = "SET_RECIPES";
export const SET_DETAILED_RECIPE = "SET_DETAILED_RECIPE";
export const SET_EDIT = "SET_EDIT";
export const DISABLE_EDIT_MODE = "DISABLE_EDIT_MODE";
export const SET_RECIPE_TITLE = "SET_RECIPE_TITLE";
export const SET_DIRECTIONS = "SET_DIRECTIONS";
export const SET_IMAGE = "SET_IMAGE";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const SET_DESCRIPTION = "SET_DESCRIPTION";


export const UPD_INGREDIENTS = "UPD_INGREDIENTS";
export const UPD_DESCRIPTION = "UPD_DESCRIPTION";
export const UPD_DIRECTIONS = "UPD_DIRECTIONS";

export const UPLOAD_RECIPE_STATUS = "UPLOAD_RECIPE_STATUS";
export const SET_RECIPE_UPLOADED = "SET_RECIPE_UPLOADED";
export const SET_NOT_LOADED = "SET_NOT_LOADED";